---

name: day 7

on: [push]

jobs:
  day_7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |-
          python -mvenv .venv
          . ./.venv/bin/activate
          pip install pytest
          pytest j.py
        working-directory: 241207

...
