---

name: day 9

on: [push]

jobs:

  day_9:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |-
          python -mvenv .venv
          . ./.venv/bin/activate
          pip install pytest
          pytest j.py && python j.py
        working-directory: 241209

...
