---

name: day 6

on:
  push:

jobs:
  6:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |-
          python -mvenv .venv
          . ./.venv/bin/activate
          pip install tqdm
          python j.py
        working-directory: 241206

...
