---

name: test

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python -mvenv .venv && . ./.venv/bin/activate

      - run: pip install pytest-cov

      - name: day 7
        run: pytest j.py
        working-directory: 241207

      - name: day 10
        run: pytest --cov --cov-report term-missing j.py
        working-directory: 241210

      - name: day 11
        run: >-
          pytest --cov --cov-report term-missing
          --doctest-modules j.py
        working-directory: 241211

      - name: day 12
        run: >-
          pytest --cov --cov-report term-missing
          --doctest-modules j.py
        working-directory: 241212

...
